// JOBFORGE Database Migration - Internal Numeric ID
// Execute this ONCE in production to migrate from TEXT composite IDs to BIGINT internal IDs

import { Pool } from 'pg';

interface MigrationResult {
  success: boolean;
  preCount: number;
  postCount: number;
  errors: string[];
  warnings: string[];
}

async function migrate(): Promise<MigrationResult> {
  const result: MigrationResult = {
    success: false,
    preCount: 0,
    postCount: 0,
    errors: [],
    warnings: [],
  };

  const connectionString = process.env.DATABASE_URL || process.env.REMOTEJOBSDB_POSTGRES_URL;
  if (!connectionString) {
    result.errors.push('DATABASE_URL not configured');
    return result;
  }

  const pool = new Pool({ connectionString, max: 1 });

  try {
    // PRE-MIGRATION: Record baseline
    console.log('=== PRE-MIGRATION INSPECTION ===');
    
    const countResult = await pool.query('SELECT COUNT(*) FROM jobs');
    result.preCount = parseInt(countResult.rows[0].count, 10);
    console.log(`Current row count: ${result.preCount}`);

    // Check current schema
    const schemaResult = await pool.query(`
      SELECT column_name, data_type, is_nullable
      FROM information_schema.columns
      WHERE table_name = 'jobs' AND column_name = 'id'
    `);
    console.log('Current id column:', JSON.stringify(schemaResult.rows[0]));

    // Check for existing internal_id column (migration already run?)
    const internalIdCheck = await pool.query(`
      SELECT column_name
      FROM information_schema.columns
      WHERE table_name = 'jobs' AND column_name = 'internal_id'
    `);

    if (internalIdCheck.rows.length > 0) {
      result.warnings.push('internal_id column already exists - migration may have been run previously');
      console.log('⚠️  WARNING: internal_id column already exists');
    }

    // Check for duplicate (source, source_job_id)
    const dupResult = await pool.query(`
      SELECT source, source_job_id, COUNT(*) as cnt
      FROM jobs
      GROUP BY source, source_job_id
      HAVING COUNT(*) > 1
    `);
    
    if (dupResult.rows.length > 0) {
      result.errors.push(`Duplicate (source, source_job_id) found: ${dupResult.rows.length} duplicates`);
      console.error('❌ Duplicate (source, source_job_id) detected:', dupResult.rows);
      return result;
    }

    console.log('✅ No duplicate (source, source_job_id) pairs');

    // BEGIN TRANSACTION
    await pool.query('BEGIN');
    console.log('\n=== MIGRATION STARTING ===');

    // Step 1: Add new internal_id column (BIGINT GENERATED BY DEFAULT AS IDENTITY)
    console.log('[1/10] Adding internal_id column...');
    await pool.query(`
      ALTER TABLE jobs
      ADD COLUMN IF NOT EXISTS internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY
    `);

    // Step 2: Verify all rows received internal_id
    console.log('[2/10] Verifying internal_id assignment...');
    const nullIdCheck = await pool.query('SELECT COUNT(*) FROM jobs WHERE internal_id IS NULL');
    const nullCount = parseInt(nullIdCheck.rows[0].count, 10);
    
    if (nullCount > 0) {
      throw new Error(`${nullCount} rows have NULL internal_id after column creation`);
    }
    console.log('✅ All rows have internal_id');

    // Step 3: Verify no duplicate internal_id
    console.log('[3/10] Checking for duplicate internal_id...');
    const dupIdCheck = await pool.query(`
      SELECT internal_id, COUNT(*) as cnt
      FROM jobs
      GROUP BY internal_id
      HAVING COUNT(*) > 1
    `);
    
    if (dupIdCheck.rows.length > 0) {
      throw new Error('Duplicate internal_id detected');
    }
    console.log('✅ No duplicate internal_id');

    // Step 4: Rename old id to old_id (preserve for reference)
    console.log('[4/10] Renaming id → old_id...');
    await pool.query('ALTER TABLE jobs RENAME COLUMN id TO old_id');

    // Step 5: Rename internal_id to id (new primary key)
    console.log('[5/10] Renaming internal_id → id...');
    await pool.query('ALTER TABLE jobs RENAME COLUMN internal_id TO id');

    // Step 6: Drop old primary key constraint
    console.log('[6/10] Dropping old primary key...');
    await pool.query('ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_pkey');

    // Step 7: Create new primary key on id
    console.log('[7/10] Creating new primary key on id...');
    await pool.query('ALTER TABLE jobs ADD PRIMARY KEY (id)');

    // Step 8: Create index on old_id for legacy lookups
    console.log('[8/10] Creating index on old_id...');
    await pool.query('CREATE INDEX IF NOT EXISTS idx_jobs_old_id ON jobs (old_id)');

    // Step 9: Verify uniqueness constraint still exists
    console.log('[9/10] Verifying UNIQUE(source, source_job_id)...');
    const uniqueCheck = await pool.query(`
      SELECT constraint_name
      FROM information_schema.table_constraints
      WHERE table_name = 'jobs'
        AND constraint_type = 'UNIQUE'
        AND constraint_name LIKE '%source%'
    `);
    
    if (uniqueCheck.rows.length === 0) {
      throw new Error('UNIQUE(source, source_job_id) constraint missing');
    }
    console.log('✅ UNIQUE(source, source_job_id) verified');

    // Step 10: Verify row count preservation
    console.log('[10/10] Verifying row count...');
    const postCountResult = await pool.query('SELECT COUNT(*) FROM jobs WHERE id IS NOT NULL');
    result.postCount = parseInt(postCountResult.rows[0].count, 10);
    
    if (result.postCount !== result.preCount) {
      throw new Error(`Row count mismatch: pre=${result.preCount}, post=${result.postCount}`);
    }
    console.log(`✅ Row count preserved: ${result.postCount}`);

    // COMMIT TRANSACTION
    await pool.query('COMMIT');
    console.log('\n✅ MIGRATION COMMITTED');

    result.success = true;

    // POST-MIGRATION VERIFICATION
    console.log('\n=== POST-MIGRATION VERIFICATION ===');

    // Sample job verification (remotive-2091140)
    const sampleJob = await pool.query(`
      SELECT id, old_id, source, source_job_id, title
      FROM jobs
      WHERE source = 'remotive' AND source_job_id = '2091140'
      LIMIT 1
    `);

    if (sampleJob.rows.length > 0) {
      console.log('Sample job (remotive-2091140):');
      console.log(JSON.stringify(sampleJob.rows[0], null, 2));
    } else {
      result.warnings.push('Sample job remotive-2091140 not found in database');
    }

    // Final statistics
    const stats = await pool.query(`
      SELECT
        COUNT(*) as total_jobs,
        COUNT(DISTINCT id) as unique_ids,
        COUNT(DISTINCT old_id) as unique_old_ids,
        COUNT(DISTINCT source || ':' || source_job_id) as unique_sources
      FROM jobs
    `);
    console.log('Final statistics:');
    console.log(JSON.stringify(stats.rows[0], null, 2));

  } catch (error) {
    await pool.query('ROLLBACK').catch(() => {});
    result.errors.push(error instanceof Error ? error.message : String(error));
    console.error('❌ MIGRATION FAILED:', error);
  } finally {
    await pool.end();
  }

  return result;
}

// Execute migration
migrate()
  .then((result) => {
    console.log('\n=== MIGRATION RESULT ===');
    console.log(`Success: ${result.success}`);
    console.log(`Pre-count: ${result.preCount}`);
    console.log(`Post-count: ${result.postCount}`);
    
    if (result.warnings.length > 0) {
      console.log('Warnings:', result.warnings);
    }
    
    if (result.errors.length > 0) {
      console.error('Errors:', result.errors);
      process.exit(1);
    }
    
    process.exit(0);
  })
  .catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
